name: "[Scala Native] Build All"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  GH_JAVA_VERSION: "21"
  GH_JAVA_DISTRIBUTION: "temurin"
  GH_SBT_OPTS: "-Xss64m -Xms4G -XX:MaxMetaspaceSize=2G -Xmx8G -XX:MaxInlineLevel=18 -XX:+UnlockExperimentalVMOptions"
  GH_JVM_OPTS: "-Xss64m -Xms4G -XX:MaxMetaspaceSize=2G -Xmx8G -XX:MaxInlineLevel=18 -XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler"
  PROJECT_NAME: "ai-skills"
  NATIVE_BIN_NAME: "aiskills"

jobs:

  native-build:
    runs-on: ${{ matrix.os.value }}
    strategy:
      matrix:
        os:
          - { name: "macOS 26 Apple Silicon", value: "macOS-26",         bin-suffix: "-macos-26-arm64" }
          - { name: "macOS 15 Apple Silicon", value: "macos-15",         bin-suffix: "-macos-15-arm64" }
          - { name: "Ubuntu ARM64",           value: "ubuntu-24.04-arm", bin-suffix: "-linux-arm64" }
          - { name: "Ubuntu Latest (x86_64)", value: "ubuntu-latest",    bin-suffix: "-linux-x86_64" }

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: ${{ env.GH_JAVA_VERSION }}
          distribution: ${{ env.GH_JAVA_DISTRIBUTION }}
          cache: sbt
      - uses: sbt/setup-sbt@v1

      - name: "Install LLVM and Clang (Ubuntu)"
        if: startsWith(matrix.os.value, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libstdc++-12-dev

      - name: "Scala Native Build on ${{ matrix.os.name }} - ${{ github.run_number }}"
        env:
          CURRENT_BRANCH_NAME: ${{ github.ref }}
          RUN_ID: ${{ github.run_id }}
          RUN_NUMBER: ${{ github.run_number }}
          JVM_OPTS: ${{ env.GH_JVM_OPTS }}
          SBT_OPTS: ${{ env.GH_SBT_OPTS }}
          APP_BIN_NAME: ${{ env.NATIVE_BIN_NAME }}${{ matrix.os.bin-suffix }}
        run: |
          echo "JVM_OPTS=${JVM_OPTS}"
          echo "SBT_OPTS=${SBT_OPTS}"
          sbt \
            -v \
            clean \
            test \
            cli/nativeLink

          NATIVE_BIN_DIR=$(ls -d modules/${{ env.PROJECT_NAME }}-cli/target/scala-*/)
          echo "NATIVE_BIN_DIR=${NATIVE_BIN_DIR}"

          echo "ls -lGh ${NATIVE_BIN_DIR}"
          ls -lGh "${NATIVE_BIN_DIR}"

          echo "mv ${NATIVE_BIN_DIR}${{ env.NATIVE_BIN_NAME }} ${NATIVE_BIN_DIR}${APP_BIN_NAME}"
          mv "${NATIVE_BIN_DIR}${{ env.NATIVE_BIN_NAME }}" "${NATIVE_BIN_DIR}${APP_BIN_NAME}"

          echo "ls -lGh ${NATIVE_BIN_DIR}"
          ls -lGh "${NATIVE_BIN_DIR}"

          "${NATIVE_BIN_DIR}${APP_BIN_NAME}" --version
          "${NATIVE_BIN_DIR}${APP_BIN_NAME}" --help
